version: '3'

services:
    chatroom_db:
        image: postgres:latest
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: 'postgres'
        volumes:
            - database_data:/var/lib/postgresql/data

volumes:
    database_data:
        driver: local
